
apiVersion: marketplace.edge-ops.dev/v1alpha1
kind: AppRelease
metadata:
  labels:
    app.kubernetes.io/name: airbus-marketplace-operator
    app.kubernetes.io/managed-by: kustomize
  name: streaming-film
spec:
  appName: streaming-film
  version: "2.4.0"
  source: s3://marketplace-artifacts-383025814770/demo-app-0.1.0.tgz
  digest: sha256:e41bd4e629a37c79cfb90a9d5622233ab35f9fa23751297dfdf71cabaef16c27
